route:
  receiver: 'default'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m

receivers:
  - name: 'default'
    webhook_configs:
      - url: 'http://bikemaster:8001/api/v1/alerts/webhook'
        send_resolved: true