"""initial_models

Revision ID: 08ee39bfe529
Revises:
Create Date: 2026-06-09 13:42:46.795874

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "08ee39bfe529"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS weather_cache")
    op.execute("DROP TABLE IF EXISTS training_stress_days")
    op.execute("DROP TABLE IF EXISTS chat_history")
    op.alter_column("athletes", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column("athletes", "name", existing_type=sa.TEXT(), type_=sa.String(length=100), existing_nullable=False)
    op.alter_column(
        "athletes", "age", existing_type=sa.INTEGER(), nullable=False, existing_server_default=sa.text("(30)")
    )
    op.alter_column(
        "athletes",
        "weight_kg",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        nullable=False,
        existing_server_default=sa.text("(70)"),
    )
    op.alter_column("athletes", "height_cm", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True)
    op.alter_column("athletes", "fat_percentage", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True)
    op.alter_column(
        "athletes", "years_active", existing_type=sa.INTEGER(), nullable=False, existing_server_default=sa.text("1")
    )
    op.alter_column(
        "athletes", "weekly_sessions", existing_type=sa.INTEGER(), nullable=False, existing_server_default=sa.text("3")
    )
    op.alter_column(
        "athletes",
        "monthly_hours",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "athletes",
        "annual_hours",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "athletes",
        "experience_level",
        existing_type=sa.TEXT(),
        type_=sa.String(length=20),
        nullable=False,
        existing_server_default=sa.text("'Beginner'"),
    )
    op.alter_column(
        "athletes", "preferred_terrain", existing_type=sa.TEXT(), type_=sa.String(length=50), existing_nullable=True
    )
    op.alter_column(
        "athletes",
        "weekly_volume_km",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column("athletes", "ftp_watts", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True)
    op.alter_column("athletes", "created_at", existing_type=sa.TEXT(), type_=sa.DateTime(), nullable=False)
    op.create_index("ix_athletes_experience_level", "athletes", ["experience_level"], unique=False)
    op.create_index("ix_athletes_name", "athletes", ["name"], unique=False)
    op.alter_column("calendar_events", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "calendar_events", "title", existing_type=sa.TEXT(), type_=sa.String(length=200), existing_nullable=False
    )
    op.alter_column(
        "calendar_events",
        "event_type",
        existing_type=sa.TEXT(),
        type_=sa.String(length=50),
        nullable=False,
        existing_server_default=sa.text("'training'"),
    )
    op.alter_column(
        "calendar_events", "date", existing_type=sa.TEXT(), type_=sa.String(length=20), existing_nullable=False
    )
    op.alter_column(
        "calendar_events",
        "duration_minutes",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "calendar_events",
        "completed",
        existing_type=sa.INTEGER(),
        type_=sa.Boolean(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column("calendar_events", "created_at", existing_type=sa.TEXT(), type_=sa.DateTime(), nullable=False)
    op.create_index(op.f("ix_calendar_events_athlete_id"), "calendar_events", ["athlete_id"], unique=False)
    op.create_index(op.f("ix_calendar_events_date"), "calendar_events", ["date"], unique=False)
    op.drop_constraint(None, "calendar_events", type_="foreignkey")
    op.add_column("metrics", sa.Column("metric_type", sa.String(length=50), nullable=False))
    op.add_column("metrics", sa.Column("value", sa.Float(), nullable=False))
    op.add_column("metrics", sa.Column("unit", sa.String(length=20), nullable=False))
    op.add_column("metrics", sa.Column("recorded_at", sa.DateTime(), nullable=False))
    op.alter_column("metrics", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column("metrics", "athlete_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_index(op.f("idx_metrics_ride"), table_name="metrics")
    op.create_index(op.f("ix_metrics_athlete_id"), "metrics", ["athlete_id"], unique=False)
    op.drop_constraint(None, "metrics", type_="foreignkey")
    op.drop_constraint(None, "metrics", type_="foreignkey")
    op.drop_column("metrics", "recovery_hours")
    op.drop_column("metrics", "fatigue_score")
    op.drop_column("metrics", "calories_per_km")
    op.drop_column("metrics", "efficiency_score")
    op.drop_column("metrics", "ride_id")
    op.drop_column("metrics", "created_at")
    op.alter_column("rides", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column("rides", "date", existing_type=sa.TEXT(), type_=sa.String(length=20), existing_nullable=False)
    op.alter_column(
        "rides",
        "distance_km",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "rides",
        "duration_minutes",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "rides",
        "avg_speed_kmh",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "rides",
        "weight_kg",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        nullable=False,
        existing_server_default=sa.text("(70)"),
    )
    op.alter_column(
        "rides",
        "calories",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column("rides", "heart_rate_avg", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True)
    op.alter_column("rides", "elevation_gain_m", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True)
    op.alter_column("rides", "created_at", existing_type=sa.TEXT(), type_=sa.DateTime(), nullable=False)
    op.drop_index(op.f("idx_rides_athlete"), table_name="rides")
    op.drop_index(op.f("idx_rides_date"), table_name="rides")
    op.drop_index(op.f("idx_rides_distance"), table_name="rides")
    op.drop_index(op.f("idx_rides_duration"), table_name="rides")
    op.drop_index(op.f("idx_rides_speed"), table_name="rides")
    op.create_index("ix_rides_athlete_date", "rides", ["athlete_id", "date"], unique=False)
    op.create_index(op.f("ix_rides_athlete_id"), "rides", ["athlete_id"], unique=False)
    op.create_index(op.f("ix_rides_date"), "rides", ["date"], unique=False)
    op.create_index("ix_rides_distance", "rides", ["distance_km"], unique=False)
    op.create_index("ix_rides_elevation", "rides", ["elevation_gain_m"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_rides_elevation", table_name="rides")
    op.drop_index("ix_rides_distance", table_name="rides")
    op.drop_index(op.f("ix_rides_date"), table_name="rides")
    op.drop_index(op.f("ix_rides_athlete_id"), table_name="rides")
    op.drop_index("ix_rides_athlete_date", table_name="rides")
    op.create_index(op.f("idx_rides_speed"), "rides", ["avg_speed_kmh"], unique=False)
    op.create_index(op.f("idx_rides_duration"), "rides", ["duration_minutes"], unique=False)
    op.create_index(op.f("idx_rides_distance"), "rides", ["distance_km"], unique=False)
    op.create_index(op.f("idx_rides_date"), "rides", ["date"], unique=False)
    op.create_index(op.f("idx_rides_athlete"), "rides", ["athlete_id"], unique=False)
    op.alter_column("rides", "created_at", existing_type=sa.DateTime(), type_=sa.TEXT(), nullable=True)
    op.alter_column("rides", "elevation_gain_m", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True)
    op.alter_column("rides", "heart_rate_avg", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True)
    op.alter_column(
        "rides",
        "calories",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "rides",
        "weight_kg",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        nullable=True,
        existing_server_default=sa.text("(70)"),
    )
    op.alter_column(
        "rides",
        "avg_speed_kmh",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "rides",
        "duration_minutes",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "rides",
        "distance_km",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column("rides", "date", existing_type=sa.String(length=20), type_=sa.TEXT(), existing_nullable=False)
    op.alter_column("rides", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.add_column("metrics", sa.Column("created_at", sa.TEXT(), nullable=True))
    op.add_column("metrics", sa.Column("ride_id", sa.INTEGER(), nullable=True))
    op.add_column("metrics", sa.Column("efficiency_score", sa.REAL(), nullable=True))
    op.add_column("metrics", sa.Column("calories_per_km", sa.REAL(), nullable=True))
    op.add_column("metrics", sa.Column("fatigue_score", sa.REAL(), nullable=True))
    op.add_column("metrics", sa.Column("recovery_hours", sa.REAL(), nullable=True))
    op.create_foreign_key(None, "metrics", "rides", ["ride_id"], ["id"])
    op.create_foreign_key(None, "metrics", "athletes", ["athlete_id"], ["id"])
    op.drop_index(op.f("ix_metrics_athlete_id"), table_name="metrics")
    op.create_index(op.f("idx_metrics_ride"), "metrics", ["ride_id"], unique=False)
    op.alter_column("metrics", "athlete_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("metrics", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.drop_column("metrics", "recorded_at")
    op.drop_column("metrics", "unit")
    op.drop_column("metrics", "value")
    op.drop_column("metrics", "metric_type")
    op.create_foreign_key(None, "calendar_events", "athletes", ["athlete_id"], ["id"])
    op.drop_index(op.f("ix_calendar_events_date"), table_name="calendar_events")
    op.drop_index(op.f("ix_calendar_events_athlete_id"), table_name="calendar_events")
    op.alter_column("calendar_events", "created_at", existing_type=sa.DateTime(), type_=sa.TEXT(), nullable=True)
    op.alter_column(
        "calendar_events",
        "completed",
        existing_type=sa.Boolean(),
        type_=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "calendar_events",
        "duration_minutes",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "calendar_events", "date", existing_type=sa.String(length=20), type_=sa.TEXT(), existing_nullable=False
    )
    op.alter_column(
        "calendar_events",
        "event_type",
        existing_type=sa.String(length=50),
        type_=sa.TEXT(),
        nullable=True,
        existing_server_default=sa.text("'training'"),
    )
    op.alter_column(
        "calendar_events", "title", existing_type=sa.String(length=200), type_=sa.TEXT(), existing_nullable=False
    )
    op.alter_column("calendar_events", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.drop_index("ix_athletes_name", table_name="athletes")
    op.drop_index("ix_athletes_experience_level", table_name="athletes")
    op.alter_column("athletes", "created_at", existing_type=sa.DateTime(), type_=sa.TEXT(), nullable=True)
    op.alter_column("athletes", "ftp_watts", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True)
    op.alter_column(
        "athletes",
        "weekly_volume_km",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "athletes", "preferred_terrain", existing_type=sa.String(length=50), type_=sa.TEXT(), existing_nullable=True
    )
    op.alter_column(
        "athletes",
        "experience_level",
        existing_type=sa.String(length=20),
        type_=sa.TEXT(),
        nullable=True,
        existing_server_default=sa.text("'Beginner'"),
    )
    op.alter_column(
        "athletes",
        "annual_hours",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "athletes",
        "monthly_hours",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "athletes", "weekly_sessions", existing_type=sa.INTEGER(), nullable=True, existing_server_default=sa.text("3")
    )
    op.alter_column(
        "athletes", "years_active", existing_type=sa.INTEGER(), nullable=True, existing_server_default=sa.text("1")
    )
    op.alter_column("athletes", "fat_percentage", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True)
    op.alter_column("athletes", "height_cm", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True)
    op.alter_column(
        "athletes",
        "weight_kg",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        nullable=True,
        existing_server_default=sa.text("(70)"),
    )
    op.alter_column(
        "athletes", "age", existing_type=sa.INTEGER(), nullable=True, existing_server_default=sa.text("(30)")
    )
    op.alter_column("athletes", "name", existing_type=sa.String(length=100), type_=sa.TEXT(), existing_nullable=False)
    op.alter_column("athletes", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_table(
        "chat_history",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("athlete_id", sa.INTEGER(), nullable=True),
        sa.Column("role", sa.TEXT(), nullable=False),
        sa.Column("content", sa.TEXT(), nullable=False),
        sa.Column("created_at", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "training_stress_days",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("athlete_id", sa.INTEGER(), nullable=False),
        sa.Column("date", sa.TEXT(), nullable=False),
        sa.Column("tss", sa.REAL(), nullable=True),
        sa.Column("atl", sa.REAL(), nullable=True),
        sa.Column("ctl", sa.REAL(), nullable=True),
        sa.Column("tsb", sa.REAL(), nullable=True),
        sa.Column("created_at", sa.TEXT(), nullable=True),
        sa.Column("updated_at", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "date"),
    )
    op.create_table(
        "weather_cache",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("lat", sa.REAL(), nullable=False),
        sa.Column("lon", sa.REAL(), nullable=False),
        sa.Column("date", sa.TEXT(), nullable=False),
        sa.Column("temperature", sa.REAL(), nullable=True),
        sa.Column("humidity", sa.REAL(), nullable=True),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("cached_at", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lat", "lon", "date"),
    )
    # ### end Alembic commands ###
