"""Add enums and missing models

Revision ID: 13a1d54d325f
Revises: ba4ede18c9fc
Create Date: 2026-07-18 01:18:13.859272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13a1d54d325f'
down_revision: Union[str, Sequence[str], None] = 'ba4ede18c9fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    _existing_tables = set(inspector.get_table_names())
    _dialect = bind.dialect.name

    # PostgreSQL-specific ENUM types — skip on SQLite where they are not supported.
    if _dialect == "postgresql":
        op.execute("""
            CREATE TYPE activitytype AS ENUM ('ride', 'run', 'hike', 'virtual_ride', 'virtual_run', 'swim', 'other');
            CREATE TYPE eventtype AS ENUM ('training', 'race', 'recovery', 'other');
            CREATE TYPE goaltype AS ENUM ('granfondo', 'marathon', 'century', 'weight_loss', 'ftp_improvement', 'general_fitness', 'race', 'other');
            CREATE TYPE incidentseverity AS ENUM ('low', 'medium', 'high', 'critical');
            CREATE TYPE poitype AS ENUM ('viewpoint', 'fountain', 'refuge', 'junction', 'danger', 'cultural', 'technical', 'parking', 'other');
            CREATE TYPE risklabel AS ENUM ('low', 'medium', 'high', 'very_high');
            CREATE TYPE userrole AS ENUM ('admin', 'user', 'client');
            CREATE TYPE workouttype AS ENUM ('endurance', 'interval', 'threshold', 'vo2max', 'recovery', 'strength', 'fartlek', 'tempo', 'other');
        """)
    op.create_table('totp_secrets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('secret', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_totp_user')
    )
    op.create_table('external_identities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('external_email', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('picture_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_external_identity')
    )
    with op.batch_alter_table('external_identities', schema=None) as batch_op:
        batch_op.create_index('ix_external_identity_athlete', ['athlete_id'], unique=False)
        batch_op.create_index('ix_external_identity_external_id', ['external_id'], unique=False)
        batch_op.create_index('ix_external_identity_provider', ['provider'], unique=False)

    op.create_table('external_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'provider', name='uq_external_token_athlete_provider')
    )
    with op.batch_alter_table('external_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_external_token_athlete', ['athlete_id'], unique=False)
        batch_op.create_index('ix_external_token_expires', ['expires_at'], unique=False)
        batch_op.create_index('ix_external_token_provider', ['provider'], unique=False)

    op.create_table('pauses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('start_index', sa.Integer(), nullable=False),
    sa.Column('end_index', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pauses', schema=None) as batch_op:
        batch_op.create_index('ix_pauses_ride_id', ['ride_id'], unique=False)

    op.create_table('segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_index', sa.Integer(), nullable=False),
    sa.Column('end_index', sa.Integer(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('avg_speed_kmh', sa.Float(), nullable=True),
    sa.Column('elevation_gain_m', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.create_index('ix_segments_ride_id', ['ride_id'], unique=False)

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())
    _dialect = bind.dialect.name

    def _has_col(table_name, col_name):
        if not inspector.has_table(table_name):
            return False
        return any(c["name"] == col_name for c in inspector.get_columns(table_name))

    def _has_idx(table_name, idx_name):
        if not inspector.has_table(table_name):
            return False
        return any(idx["name"] == idx_name for idx in inspector.get_indexes(table_name))

    def _has_fk(table_name, fk_name):
        if not inspector.has_table(table_name):
            return False
        return any(fk["name"] == fk_name for fk in inspector.get_foreign_keys(table_name))

    def _add_idx(table_name, idx_name, cols):
        if not _has_idx(table_name, idx_name):
            op.create_index(idx_name, table_name, cols, unique=False)

    if "social_accounts" in existing_tables:
        op.drop_table('social_accounts')
    if "posts" in existing_tables:
        op.drop_table('posts')

    # --- athletes indexes ---
    _add_idx('athletes', 'ix_athletes_email', ['email'])
    _add_idx('athletes', 'ix_athletes_experience_level', ['experience_level'])
    _add_idx('athletes', 'ix_athletes_name', ['name'])
    _add_idx('athletes', 'ix_athletes_tenant', ['tenant_id'])
    if _has_col('athletes', 'user_id'):
        _add_idx('athletes', 'ix_athletes_user_id', ['user_id'])

    # --- calendar_events ---
    _add_idx('calendar_events', 'ix_calendar_events_athlete_date', ['athlete_id', 'date'])
    _add_idx('calendar_events', 'ix_calendar_events_date', ['date'])
    _add_idx('calendar_events', 'ix_calendar_events_tenant', ['tenant_id'])
    if _dialect == "postgresql":
        op.execute("ALTER TABLE calendar_events ALTER COLUMN event_type TYPE eventtype USING event_type::eventtype")

    # --- metrics indexes ---
    _add_idx('metrics', 'ix_metrics_athlete_id', ['athlete_id'])
    _add_idx('metrics', 'ix_metrics_ride_id', ['ride_id'])
    _add_idx('metrics', 'ix_metrics_tenant', ['tenant_id'])

    # --- planned_workouts ---
    _add_idx('planned_workouts', 'ix_planned_workouts_athlete', ['athlete_id'])
    _add_idx('planned_workouts', 'ix_planned_workouts_completed', ['completed'])
    _add_idx('planned_workouts', 'ix_planned_workouts_date', ['date'])
    _add_idx('planned_workouts', 'ix_planned_workouts_goal', ['goal_id'])
    _add_idx('planned_workouts', 'ix_planned_workouts_tenant', ['tenant_id'])
    if _dialect == "postgresql":
        op.execute("ALTER TABLE planned_workouts ALTER COLUMN workout_type TYPE workouttype USING workout_type::workouttype")

    # --- pois ---
    _add_idx('pois', 'idx_pois_coords', ['lat', 'lon'])
    _add_idx('pois', 'ix_pois_tenant', ['tenant_id'])
    _add_idx('pois', 'ix_pois_type', ['type'])
    if _dialect == "postgresql":
        op.execute("ALTER TABLE pois ALTER COLUMN type TYPE poitype USING type::poitype")
    else:
        # SQLite: recreate FK with CASCADE via batch mode
        if not _has_fk('pois', 'fk_pois_created_by'):
            with op.batch_alter_table('pois', schema=None) as batch_op:
                _fks = inspector.get_foreign_keys('pois')
                for fk in _fks:
                    if 'created_by' in fk.get('constrained_columns', []) and fk['name']:
                        batch_op.drop_constraint(fk['name'], type_='foreignkey')
                batch_op.create_foreign_key('fk_pois_created_by', 'athletes', ['created_by'], ['id'], ondelete='SET NULL')

    # --- rides ---
    _add_idx('rides', 'ix_rides_athlete_id', ['athlete_id'])
    _add_idx('rides', 'ix_rides_date', ['date'])
    _add_idx('rides', 'ix_rides_tenant', ['tenant_id'])
    if _dialect == "postgresql":
        op.execute("ALTER TABLE rides ALTER COLUMN activity_type TYPE activitytype USING activity_type::activitytype")

    # --- road_incidents ---
    _add_idx('road_incidents', 'ix_road_incidents_coords', ['lat', 'lon'])
    _add_idx('road_incidents', 'ix_road_incidents_severity', ['severity'])
    _add_idx('road_incidents', 'ix_road_incidents_source', ['source'])
    if _dialect == "postgresql":
        op.execute("ALTER TABLE road_incidents ALTER COLUMN severity TYPE incidentseverity USING severity::incidentseverity")

    # --- route_safety_scores ---
    _add_idx('route_safety_scores', 'ix_route_safety_scores_athlete', ['athlete_id'])
    _add_idx('route_safety_scores', 'ix_route_safety_scores_ride', ['ride_id'])
    _add_idx('route_safety_scores', 'ix_route_safety_scores_tenant', ['tenant_id'])
    if _dialect == "postgresql":
        op.execute("ALTER TABLE route_safety_scores ALTER COLUMN label TYPE risklabel USING label::risklabel")

    # --- training_goals ---
    _add_idx('training_goals', 'ix_training_goals_athlete', ['athlete_id'])
    _add_idx('training_goals', 'ix_training_goals_status', ['status'])
    _add_idx('training_goals', 'ix_training_goals_tenant', ['tenant_id'])
    if _dialect == "postgresql":
        op.execute("ALTER TABLE training_goals ALTER COLUMN goal_type TYPE goaltype USING goal_type::goaltype")

    # --- training_stress_days ---
    _add_idx('training_stress_days', 'ix_training_stress_days_athlete', ['athlete_id'])
    _add_idx('training_stress_days', 'ix_training_stress_days_date', ['date'])
    _add_idx('training_stress_days', 'ix_training_stress_days_tenant', ['tenant_id'])

    # --- users: add role column + indexes ---
    if not _has_col('users', 'role'):
        if _dialect == "postgresql":
            op.add_column('users', sa.Column('role', sa.Enum('admin', 'user', 'client', name='userrole'), nullable=False, server_default='user'))
        else:
            op.add_column('users', sa.Column('role', sa.String(), nullable=False, server_default='user'))
    if _has_col('users', 'role'):
        op.alter_column('users', 'role', server_default=None)
    _add_idx('users', 'ix_users_email', ['email'])
    _add_idx('users', 'ix_users_is_active', ['is_active'])
    _add_idx('users', 'ix_users_username', ['username'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DROP TYPE IF EXISTS workouttype;
        DROP TYPE IF EXISTS userrole;
        DROP TYPE IF EXISTS risklabel;
        DROP TYPE IF EXISTS poitype;
        DROP TYPE IF EXISTS incidentseverity;
        DROP TYPE IF EXISTS goaltype;
        DROP TYPE IF EXISTS eventtype;
        DROP TYPE IF EXISTS activitytype;
    """)
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_username')
        batch_op.drop_index('ix_users_is_active')
        batch_op.drop_index('ix_users_email')
        batch_op.drop_column('role')

    with op.batch_alter_table('training_stress_days', schema=None) as batch_op:
        batch_op.drop_index('ix_training_stress_days_tenant')
        batch_op.drop_index('ix_training_stress_days_date')
        batch_op.drop_index('ix_training_stress_days_athlete')

    with op.batch_alter_table('training_goals', schema=None) as batch_op:
        batch_op.drop_index('ix_training_goals_tenant')
        batch_op.drop_index('ix_training_goals_status')
        batch_op.drop_index('ix_training_goals_athlete')
        batch_op.alter_column('goal_type',
               existing_type=sa.Enum('granfondo', 'marathon', 'century', 'weight_loss', 'ftp_improvement', 'general_fitness', 'race', 'other', name='goaltype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('route_safety_scores', schema=None) as batch_op:
        batch_op.drop_index('ix_route_safety_scores_tenant')
        batch_op.drop_index('ix_route_safety_scores_ride')
        batch_op.drop_index('ix_route_safety_scores_athlete')
        batch_op.alter_column('label',
               existing_type=sa.Enum('low', 'medium', 'high', 'very_high', name='risklabel'),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('road_incidents', schema=None) as batch_op:
        batch_op.drop_index('ix_road_incidents_source')
        batch_op.drop_index('ix_road_incidents_severity')
        batch_op.drop_index('ix_road_incidents_coords')
        batch_op.alter_column('severity',
               existing_type=sa.Enum('low', 'medium', 'high', 'critical', name='incidentseverity'),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.drop_index('ix_rides_tenant')
        batch_op.drop_index('ix_rides_date')
        batch_op.drop_index('ix_rides_athlete_id')
        batch_op.alter_column('activity_type',
               existing_type=sa.Enum('ride', 'run', 'hike', 'virtual_ride', 'virtual_run', 'swim', 'other', name='activitytype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('pois', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pois_created_by_fkey'), 'users', ['created_by'], ['id'], ondelete='SET NULL')
        batch_op.drop_index('ix_pois_type')
        batch_op.drop_index('ix_pois_tenant')
        batch_op.drop_index('idx_pois_coords')
        batch_op.alter_column('type',
               existing_type=sa.Enum('viewpoint', 'fountain', 'refuge', 'junction', 'danger', 'cultural', 'technical', 'parking', 'other', name='poitype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('planned_workouts', schema=None) as batch_op:
        batch_op.drop_index('ix_planned_workouts_tenant')
        batch_op.drop_index('ix_planned_workouts_goal')
        batch_op.drop_index('ix_planned_workouts_date')
        batch_op.drop_index('ix_planned_workouts_completed')
        batch_op.drop_index('ix_planned_workouts_athlete')
        batch_op.alter_column('workout_type',
               existing_type=sa.Enum('endurance', 'interval', 'threshold', 'vo2max', 'recovery', 'strength', 'fartlek', 'tempo', 'other', name='workouttype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.drop_index('ix_metrics_tenant')
        batch_op.drop_index('ix_metrics_ride_id')
        batch_op.drop_index('ix_metrics_athlete_id')

    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_index('ix_calendar_events_tenant')
        batch_op.drop_index('ix_calendar_events_date')
        batch_op.drop_index('ix_calendar_events_athlete_date')
        batch_op.alter_column('event_type',
               existing_type=sa.Enum('training', 'race', 'recovery', 'other', name='eventtype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('athletes', schema=None) as batch_op:
        batch_op.drop_index('ix_athletes_user_id')
        batch_op.drop_index('ix_athletes_tenant')
        batch_op.drop_index('ix_athletes_name')
        batch_op.drop_index('ix_athletes_experience_level')
        batch_op.drop_index('ix_athletes_email')

    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('platforms', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'draft'::text"), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('posts_pkey'))
    )
    op.create_table('social_accounts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('account_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('connected', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('social_accounts_pkey'))
    )
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.drop_index('ix_segments_ride_id')

    op.drop_table('segments')
    with op.batch_alter_table('pauses', schema=None) as batch_op:
        batch_op.drop_index('ix_pauses_ride_id')

    op.drop_table('pauses')
    with op.batch_alter_table('external_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_external_token_provider')
        batch_op.drop_index('ix_external_token_expires')
        batch_op.drop_index('ix_external_token_athlete')

    op.drop_table('external_tokens')
    with op.batch_alter_table('external_identities', schema=None) as batch_op:
        batch_op.drop_index('ix_external_identity_provider')
        batch_op.drop_index('ix_external_identity_external_id')
        batch_op.drop_index('ix_external_identity_athlete')

    op.drop_table('external_identities')
    op.drop_table('totp_secrets')
    # ### end Alembic commands ###
