"""sync_models_expansion

Revision ID: ba4ede18c9fc
Revises: add_is_client_col
Create Date: 2026-07-18 00:05:11.849104

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import postgresql
from alembic import op

revision: str = 'ba4ede18c9fc'
down_revision: Union[str, Sequence[str], None] = 'add_is_client_col'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = inspect(bind)
    _existing_tables = set(inspector.get_table_names())
    # ### commands auto generated by Alembic - please adjust! ###
    if 'audit_logs' not in _existing_tables:
        op.create_table('audit_logs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('actor_id', sa.Integer(), nullable=True),
        sa.Column('action', sa.String(), nullable=False),
        sa.Column('resource', sa.String(), nullable=False),
        sa.Column('resource_id', sa.Integer(), nullable=True),
        sa.Column('details', sa.Text(), nullable=False),
        sa.Column('ip_address', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if 'road_incidents' not in _existing_tables:
        op.create_table('road_incidents',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('source_id', sa.String(), nullable=False),
        sa.Column('lat', sa.Float(), nullable=False),
        sa.Column('lon', sa.Float(), nullable=False),
        sa.Column('incident_date', sa.String(), nullable=False),
        sa.Column('severity', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('road_type', sa.String(), nullable=True),
        sa.Column('source', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('source_id', 'source', name='uq_road_incidents')
        )
    if 'sync_conflicts' not in _existing_tables:
        op.create_table('sync_conflicts',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('entity_type', sa.String(), nullable=False),
        sa.Column('entity_id', sa.Integer(), nullable=False),
        sa.Column('local_data', sa.Text(), nullable=False),
        sa.Column('remote_data', sa.Text(), nullable=False),
        sa.Column('local_reliability', sa.Float(), nullable=False),
        sa.Column('remote_reliability', sa.Float(), nullable=False),
        sa.Column('local_modified', sa.DateTime(timezone=True), nullable=False),
        sa.Column('remote_modified', sa.DateTime(timezone=True), nullable=False),
        sa.Column('resolution', sa.String(), nullable=False),
        sa.Column('resolved_data', sa.Text(), nullable=True),
        sa.Column('resolution_reason', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if 'sync_entity_state' not in _existing_tables:
        op.create_table('sync_entity_state',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('entity_type', sa.String(), nullable=False),
        sa.Column('entity_id', sa.Integer(), nullable=False),
        sa.Column('source', sa.String(), nullable=False),
        sa.Column('reliability_score', sa.Float(), nullable=False),
        sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
        sa.Column('sync_status', sa.String(), nullable=False),
        sa.Column('sync_error', sa.Text(), nullable=True),
        sa.Column('cloud_id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('entity_type', 'entity_id', name='uq_sync_entity_state')
        )
    if 'sync_settings' not in _existing_tables:
        op.create_table('sync_settings',
        sa.Column('key', sa.String(), nullable=False),
        sa.Column('value', sa.String(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('key')
        )
    if 'weather_cache' not in _existing_tables:
        op.create_table('weather_cache',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('lat', sa.Float(), nullable=False),
        sa.Column('lon', sa.Float(), nullable=False),
        sa.Column('date', sa.String(), nullable=False),
        sa.Column('temperature', sa.Float(), nullable=True),
        sa.Column('humidity', sa.Float(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('cached_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('lat', 'lon', 'date', name='uq_weather_cache')
        )
    if 'calendar_events' not in _existing_tables:
        op.create_table('calendar_events',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('athlete_id', sa.Integer(), nullable=True),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('event_type', sa.String(), nullable=False),
        sa.Column('date', sa.String(), nullable=False),
        sa.Column('duration_minutes', sa.Integer(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('completed', sa.Boolean(), nullable=False),
        sa.Column('weather_temp', sa.Float(), nullable=True),
        sa.Column('weather_humidity', sa.Float(), nullable=True),
        sa.Column('weather_description', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if inspector.has_table('calendar_events'):
        _idx = {idx["name"] for idx in inspector.get_indexes('calendar_events')}
        if 'ix_calendar_events_athlete_id' not in _idx:
            op.create_index('ix_calendar_events_athlete_id', 'calendar_events', ['athlete_id'], unique=False)

    if 'garmin_tokens' not in _existing_tables:
        op.create_table('garmin_tokens',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('athlete_id', sa.Integer(), nullable=False),
        sa.Column('access_token', sa.String(length=1024), nullable=False),
        sa.Column('refresh_token', sa.String(length=1024), nullable=False),
        sa.Column('expires_at', sa.Integer(), nullable=True),
        sa.Column('scope', sa.String(length=200), nullable=True),
        sa.Column('athlete_name', sa.String(length=200), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('athlete_id')
        )
    if 'sessions' not in _existing_tables:
        op.create_table('sessions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('athlete_id', sa.Integer(), nullable=False),
        sa.Column('refresh_token', sa.String(), nullable=False),
        sa.Column('jti', sa.String(), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('jti'),
        sa.UniqueConstraint('refresh_token')
        )
    if inspector.has_table('sessions'):
        _idx = {idx["name"] for idx in inspector.get_indexes('sessions')}
        if 'ix_sessions_athlete_id' not in _idx:
            op.create_index('ix_sessions_athlete_id', 'sessions', ['athlete_id'], unique=False)

    if 'strava_tokens' not in _existing_tables:
        op.create_table('strava_tokens',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('athlete_id', sa.Integer(), nullable=False),
        sa.Column('access_token', sa.String(length=1024), nullable=False),
        sa.Column('refresh_token', sa.String(length=1024), nullable=False),
        sa.Column('expires_at', sa.Integer(), nullable=True),
        sa.Column('scope', sa.String(length=200), nullable=True),
        sa.Column('athlete_name', sa.String(length=200), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('athlete_id')
        )
    if 'training_stress_days' not in _existing_tables:
        op.create_table('training_stress_days',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('athlete_id', sa.Integer(), nullable=False),
        sa.Column('date', sa.String(), nullable=False),
        sa.Column('tss', sa.Float(), nullable=True),
        sa.Column('atl', sa.Float(), nullable=True),
        sa.Column('ctl', sa.Float(), nullable=True),
        sa.Column('tsb', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('athlete_id', 'date', name='uq_training_stress_days')
        )
    if 'metrics' not in _existing_tables:
        op.create_table('metrics',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('athlete_id', sa.Integer(), nullable=True),
        sa.Column('ride_id', sa.Integer(), nullable=True),
        sa.Column('fatigue_score', sa.Float(), nullable=True),
        sa.Column('recovery_hours', sa.Float(), nullable=True),
        sa.Column('calories_per_km', sa.Float(), nullable=True),
        sa.Column('efficiency_score', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('ride_id')
        )
    if 'route_safety_scores' not in _existing_tables:
        op.create_table('route_safety_scores',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('ride_id', sa.Integer(), nullable=True),
        sa.Column('athlete_id', sa.Integer(), nullable=True),
        sa.Column('risk_score', sa.Float(), nullable=True),
        sa.Column('label', sa.String(), nullable=True),
        sa.Column('advice', sa.Text(), nullable=True),
        sa.Column('road_type_counts', sa.Text(), nullable=True),
        sa.Column('has_bike_infrastructure', sa.Boolean(), nullable=True),
        sa.Column('incident_count', sa.Integer(), nullable=True),
        sa.Column('route_length_km', sa.Float(), nullable=True),
        sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    bind = op.get_bind()
    inspector = inspect(bind)
    is_sqlite = bind.dialect.name == "sqlite"

    def _col_exists(table_name: str, column_name: str) -> bool:
        if not inspector.has_table(table_name):
            return False
        return any(c["name"] == column_name for c in inspector.get_columns(table_name))

    def _fk_exists(table_name: str, fk_name: str) -> bool:
        if not inspector.has_table(table_name):
            return False
        return any(fk["name"] == fk_name for fk in inspector.get_foreign_keys(table_name))

    def _uq_exists(table_name: str, uq_name: str) -> bool:
        if not inspector.has_table(table_name):
            return False
        return any(c["name"] == uq_name for c in inspector.get_unique_constraints(table_name))

    def _idx_exists(table_name: str, idx_name: str) -> bool:
        if not inspector.has_table(table_name):
            return False
        return any(idx["name"] == idx_name for idx in inspector.get_indexes(table_name))

    if is_sqlite:
        # SQLite requires batch mode for constraint operations
        if not _col_exists("athletes", "user_id"):
            with op.batch_alter_table("athletes", schema=None) as batch_op:
                batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
                if not _uq_exists("athletes", "uq_athletes_user_id"):
                    batch_op.create_unique_constraint("uq_athletes_user_id", ["user_id"])
                if not _fk_exists("athletes", "fk_athletes_user_id"):
                    batch_op.create_foreign_key("fk_athletes_user_id", "users", ["user_id"], ["id"], ondelete="CASCADE")

        if inspector.has_table("chat_history") and not _fk_exists("chat_history", "fk_chat_history_athlete_id"):
            with op.batch_alter_table("chat_history", schema=None) as batch_op:
                batch_op.create_foreign_key("fk_chat_history_athlete_id", "athletes", ["athlete_id"], ["id"], ondelete="CASCADE")

        if inspector.has_table("fitness_states"):
            with op.batch_alter_table("fitness_states", schema=None) as batch_op:
                for fk in inspector.get_foreign_keys("fitness_states"):
                    if "athlete_id" in fk.get("constrained_columns", []) and fk["name"]:
                        batch_op.drop_constraint(fk["name"], type_="foreignkey")
                if not _fk_exists("fitness_states", "fk_fitness_states_athlete_id"):
                    batch_op.create_foreign_key("fk_fitness_states_athlete_id", "athletes", ["athlete_id"], ["id"], ondelete="CASCADE")

        if not _col_exists("knowledge_chunks", "tenant_id"):
            with op.batch_alter_table("knowledge_chunks", schema=None) as batch_op:
                batch_op.add_column(sa.Column("tenant_id", sa.Integer(), nullable=False, server_default="0"))
                batch_op.add_column(sa.Column("created_at", sa.DateTime(timezone=True), nullable=True))
                batch_op.alter_column("tenant_id", server_default=None)

        if inspector.has_table("planned_workouts"):
            with op.batch_alter_table("planned_workouts", schema=None) as batch_op:
                for fk in inspector.get_foreign_keys("planned_workouts"):
                    cols = fk.get("constrained_columns", [])
                    if ("athlete_id" in cols or "goal_id" in cols) and fk["name"]:
                        batch_op.drop_constraint(fk["name"], type_="foreignkey")
                batch_op.alter_column("athlete_id", existing_type=sa.INTEGER(), nullable=False)
                if not _fk_exists("planned_workouts", "fk_pw_goal_id"):
                    batch_op.create_foreign_key("fk_pw_goal_id", "training_goals", ["goal_id"], ["id"], ondelete="SET NULL")
                if not _fk_exists("planned_workouts", "fk_pw_athlete_id"):
                    batch_op.create_foreign_key("fk_pw_athlete_id", "athletes", ["athlete_id"], ["id"], ondelete="CASCADE")

        if inspector.has_table("pois") and not _fk_exists("pois", "fk_pois_created_by"):
            with op.batch_alter_table("pois", schema=None) as batch_op:
                batch_op.create_foreign_key("fk_pois_created_by", "users", ["created_by"], ["id"], ondelete="SET NULL")

        if not _col_exists("rides", "updated_at"):
            op.add_column("rides", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
        if inspector.has_table("rides") and not _fk_exists("rides", "fk_rides_athlete_id"):
            with op.batch_alter_table("rides", schema=None) as batch_op:
                batch_op.create_foreign_key("fk_rides_athlete_id", "athletes", ["athlete_id"], ["id"], ondelete="CASCADE")

        if inspector.has_table("training_goals"):
            with op.batch_alter_table("training_goals", schema=None) as batch_op:
                for fk in inspector.get_foreign_keys("training_goals"):
                    if "athlete_id" in fk.get("constrained_columns", []) and fk["name"]:
                        batch_op.drop_constraint(fk["name"], type_="foreignkey")
                batch_op.alter_column("athlete_id", existing_type=sa.INTEGER(), nullable=False)
                if not _fk_exists("training_goals", "fk_tg_athlete_id"):
                    batch_op.create_foreign_key("fk_tg_athlete_id", "athletes", ["athlete_id"], ["id"], ondelete="CASCADE")
    else:
        # PostgreSQL: direct operations
        if not _col_exists("athletes", "user_id"):
            op.add_column("athletes", sa.Column("user_id", sa.Integer(), nullable=True))
        if not _uq_exists("athletes", "uq_athletes_user_id"):
            op.create_unique_constraint("uq_athletes_user_id", "athletes", ["user_id"])
        if not _fk_exists("athletes", "fk_athletes_user_id"):
            op.create_foreign_key("fk_athletes_user_id", "users", "athletes", ["user_id"], ["id"], ondelete="CASCADE")

        if inspector.has_table("chat_history") and not _fk_exists("chat_history", "fk_chat_history_athlete_id"):
            op.create_foreign_key("fk_chat_history_athlete_id", "athletes", "chat_history", ["athlete_id"], ["id"], ondelete="CASCADE")

        if inspector.has_table("fitness_states"):
            for fk in inspector.get_foreign_keys("fitness_states"):
                if "athlete_id" in fk.get("constrained_columns", []):
                    op.drop_constraint(fk["name"], "fitness_states", type_="foreignkey")
            if not _fk_exists("fitness_states", "fk_fitness_states_athlete_id"):
                op.create_foreign_key("fk_fitness_states_athlete_id", "athletes", "fitness_states", ["athlete_id"], ["id"], ondelete="CASCADE")

        if not _col_exists("knowledge_chunks", "tenant_id"):
            op.add_column("knowledge_chunks", sa.Column("tenant_id", sa.Integer(), nullable=False, server_default="0"))
        if not _col_exists("knowledge_chunks", "created_at"):
            op.add_column("knowledge_chunks", sa.Column("created_at", sa.DateTime(timezone=True), nullable=True))
        if _col_exists("knowledge_chunks", "tenant_id"):
            op.alter_column("knowledge_chunks", "tenant_id", server_default=None)

        if inspector.has_table("planned_workouts"):
            for fk in inspector.get_foreign_keys("planned_workouts"):
                cols = fk.get("constrained_columns", [])
                if "athlete_id" in cols or "goal_id" in cols:
                    op.drop_constraint(fk["name"], "planned_workouts", type_="foreignkey")
            op.alter_column("planned_workouts", "athlete_id", existing_type=sa.INTEGER(), nullable=False)
            if not _fk_exists("planned_workouts", "fk_pw_goal_id"):
                op.create_foreign_key("fk_pw_goal_id", "training_goals", "planned_workouts", ["goal_id"], ["id"], ondelete="SET NULL")
            if not _fk_exists("planned_workouts", "fk_pw_athlete_id"):
                op.create_foreign_key("fk_pw_athlete_id", "athletes", "planned_workouts", ["athlete_id"], ["id"], ondelete="CASCADE")

        if inspector.has_table("pois") and not _fk_exists("pois", "fk_pois_created_by"):
            op.create_foreign_key("fk_pois_created_by", "users", "pois", ["created_by"], ["id"], ondelete="SET NULL")

        if not _col_exists("rides", "updated_at"):
            op.add_column("rides", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
        if inspector.has_table("rides") and not _fk_exists("rides", "fk_rides_athlete_id"):
            op.create_foreign_key("fk_rides_athlete_id", "athletes", "rides", ["athlete_id"], ["id"], ondelete="CASCADE")

        if inspector.has_table("training_goals"):
            for fk in inspector.get_foreign_keys("training_goals"):
                if "athlete_id" in fk.get("constrained_columns", []):
                    op.drop_constraint(fk["name"], "training_goals", type_="foreignkey")
            op.alter_column("training_goals", "athlete_id", existing_type=sa.INTEGER(), nullable=False)
            if not _fk_exists("training_goals", "fk_tg_athlete_id"):
                op.create_foreign_key("fk_tg_athlete_id", "athletes", "training_goals", ["athlete_id"], ["id"], ondelete="CASCADE")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_goals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('training_goals_athlete_id_fkey'), 'athletes', ['athlete_id'], ['id'])
        batch_op.alter_column('athlete_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('pois', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('planned_workouts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('planned_workouts_goal_id_fkey'), 'training_goals', ['goal_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('planned_workouts_athlete_id_fkey'), 'athletes', ['athlete_id'], ['id'])
        batch_op.alter_column('athlete_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('fitness_states', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fitness_states_athlete_id_fkey'), 'athletes', ['athlete_id'], ['id'])

    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('athletes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_id')

    op.drop_table('route_safety_scores')
    op.drop_table('metrics')
    op.drop_table('training_stress_days')
    op.drop_table('strava_tokens')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_athlete_id'))

    op.drop_table('sessions')
    op.drop_table('garmin_tokens')
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_events_athlete_id'))

    op.drop_table('calendar_events')
    op.drop_table('weather_cache')
    op.drop_table('sync_settings')
    op.drop_table('sync_entity_state')
    op.drop_table('sync_conflicts')
    op.drop_table('road_incidents')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
