"""sync_models_expansion

Revision ID: ba4ede18c9fc
Revises: add_is_client_col
Create Date: 2026-07-18 00:05:11.849104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba4ede18c9fc'
down_revision: Union[str, Sequence[str], None] = 'add_is_client_col'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('road_incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('incident_date', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('road_type', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source', name='uq_road_incidents')
    )
    op.create_table('sync_conflicts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('local_data', sa.Text(), nullable=False),
    sa.Column('remote_data', sa.Text(), nullable=False),
    sa.Column('local_reliability', sa.Float(), nullable=False),
    sa.Column('remote_reliability', sa.Float(), nullable=False),
    sa.Column('local_modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('remote_modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolution', sa.String(), nullable=False),
    sa.Column('resolved_data', sa.Text(), nullable=True),
    sa.Column('resolution_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_entity_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_status', sa.String(), nullable=False),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('cloud_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_sync_entity_state')
    )
    op.create_table('sync_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('weather_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('cached_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lat', 'lon', 'date', name='uq_weather_cache')
    )
    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('weather_temp', sa.Float(), nullable=True),
    sa.Column('weather_humidity', sa.Float(), nullable=True),
    sa.Column('weather_description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_events_athlete_id'), ['athlete_id'], unique=False)

    op.create_table('garmin_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=1024), nullable=False),
    sa.Column('refresh_token', sa.String(length=1024), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('scope', sa.String(length=200), nullable=True),
    sa.Column('athlete_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti'),
    sa.UniqueConstraint('refresh_token')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_athlete_id'), ['athlete_id'], unique=False)

    op.create_table('strava_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=1024), nullable=False),
    sa.Column('refresh_token', sa.String(length=1024), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('scope', sa.String(length=200), nullable=True),
    sa.Column('athlete_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id')
    )
    op.create_table('training_stress_days',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('tss', sa.Float(), nullable=True),
    sa.Column('atl', sa.Float(), nullable=True),
    sa.Column('ctl', sa.Float(), nullable=True),
    sa.Column('tsb', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'date', name='uq_training_stress_days')
    )
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('ride_id', sa.Integer(), nullable=True),
    sa.Column('fatigue_score', sa.Float(), nullable=True),
    sa.Column('recovery_hours', sa.Float(), nullable=True),
    sa.Column('calories_per_km', sa.Float(), nullable=True),
    sa.Column('efficiency_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ride_id')
    )
    op.create_table('route_safety_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=True),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('advice', sa.Text(), nullable=True),
    sa.Column('road_type_counts', sa.Text(), nullable=True),
    sa.Column('has_bike_infrastructure', sa.Boolean(), nullable=True),
    sa.Column('incident_count', sa.Integer(), nullable=True),
    sa.Column('route_length_km', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('athletes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'athletes', ['athlete_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('fitness_states', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fitness_states_athlete_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'athletes', ['athlete_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('tenant_id', server_default=None)

    with op.batch_alter_table('planned_workouts', schema=None) as batch_op:
        batch_op.alter_column('athlete_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('planned_workouts_athlete_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('planned_workouts_goal_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'training_goals', ['goal_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'athletes', ['athlete_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('pois', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key(None, 'athletes', ['athlete_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('training_goals', schema=None) as batch_op:
        batch_op.alter_column('athlete_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('training_goals_athlete_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'athletes', ['athlete_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_goals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('training_goals_athlete_id_fkey'), 'athletes', ['athlete_id'], ['id'])
        batch_op.alter_column('athlete_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('pois', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('planned_workouts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('planned_workouts_goal_id_fkey'), 'training_goals', ['goal_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('planned_workouts_athlete_id_fkey'), 'athletes', ['athlete_id'], ['id'])
        batch_op.alter_column('athlete_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('fitness_states', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fitness_states_athlete_id_fkey'), 'athletes', ['athlete_id'], ['id'])

    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('athletes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_id')

    op.drop_table('route_safety_scores')
    op.drop_table('metrics')
    op.drop_table('training_stress_days')
    op.drop_table('strava_tokens')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_athlete_id'))

    op.drop_table('sessions')
    op.drop_table('garmin_tokens')
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_events_athlete_id'))

    op.drop_table('calendar_events')
    op.drop_table('weather_cache')
    op.drop_table('sync_settings')
    op.drop_table('sync_entity_state')
    op.drop_table('sync_conflicts')
    op.drop_table('road_incidents')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
