plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-parcelize'
}

android {
    namespace 'com.bikemaster'
    compileSdk 34

    defaultConfig {
        applicationId "com.bikemaster"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
}

dependencies {
    implementation project(':capacitor')
    implementation 'com.getcapacitor:capacitor:5.7.4'
}