"""AetherMap core package — Phase 1 mathematical Earth model.

Exports:
    coordinates: Geodetic, ECEF, CubeCell, conversions, distances
    cube_sphere: CubeSphereCell, face mapping, quadtree, neighbors
    spatial_hierarchy: S2/H3 hierarchy ops, region covering
    earth_model: EarthParams, Heightfield, geoid, gravity
"""

from aethermap.core.coordinates import (
    ECEF,
    CubeCell,
    Geodetic,
    geodetic_bearing,
    geodetic_to_cube,
    geodetic_to_direction,
    geodetic_to_ecef,
    h3_cell,
    haversine_distance,
    interpolate_geodetic,
    parse_cube_cell_id,
    s2_cell_id,
)
from aethermap.core.cube_sphere import (
    CubeSphereCell,
    cell_area,
    cell_center_geodetic,
    cell_direction,
    cell_ground_resolution,
    cell_neighbors,
    direction_to_face_uv,
    face_at_level,
    face_uv_to_direction,
    latlon_to_cell,
    level_for_cell_count,
    level_for_resolution,
    root_cells,
    subdivide_to_level,
)
from aethermap.core.earth_model import (
    EARTH,
    EARTH_RADIUS_AUTHALIC,
    EARTH_RADIUS_MEAN,
    EARTH_RADIUS_VOLUMETRIC,
    CompositeHeightfield,
    GeoidModel,
    Heightfield,
    HeightSample,
    ProceduralHeightfield,
    geoid_height,
    gravity_wgs84,
    set_geoid,
)
from aethermap.core.spatial_hierarchy import (
    cube_cell_id_to_s2,
    h3_children,
    h3_compact,
    h3_index_to_latlon,
    h3_is_ancestor,
    h3_is_valid_index,
    h3_latlon_to_index,
    h3_level_from_index,
    h3_parent,
    h3_region_cover,
    h3_resolution_to_s2_level,
    s2_is_ancestor,
    s2_is_valid_token,
    s2_latlon_to_token,
    s2_level_from_token,
    s2_level_to_h3_resolution,
    s2_parent,
    s2_region_cover,
    s2_to_cube_sphere,
    s2_token_to_latlon,
)

__all__ = [
    # coordinates
    "CubeCell",
    "ECEF",
    "Geodetic",
    "cube_cell_id",
    "cube_to_geodetic",
    "direction_to_geodetic",
    "ecef_to_cube",
    "ecef_to_direction",
    "ecef_to_geodetic",
    "ecef_to_geodetic_direction",
    "ellipsoid_area",
    "ellipsoid_radius",
    "ellipsoid_radius_of_curvature",
    "geodetic_bearing",
    "geodetic_to_cube",
    "geodetic_to_direction",
    "geodetic_to_ecef",
    "h3_cell",
    "haversine_distance",
    "interpolate_geodetic",
    "parse_cube_cell_id",
    "s2_cell_id",
    # cube_sphere
    "CubeSphereCell",
    "cell_area",
    "cell_center_geodetic",
    "cell_direction",
    "cell_ground_resolution",
    "cell_neighbors",
    "direction_to_face_uv",
    "face_uv_to_direction",
    "face_at_level",
    "latlon_to_cell",
    "level_for_cell_count",
    "level_for_resolution",
    "root_cells",
    "subdivide_to_level",
    # earth_model
    "EARTH",
    "EARTH_RADIUS_AUTHALIC",
    "EARTH_RADIUS_MEAN",
    "EARTH_RADIUS_VOLUMETRIC",
    "CompositeHeightfield",
    "GeoidModel",
    "HeightSample",
    "Heightfield",
    "ProceduralHeightfield",
    "gravity_wgs84",
    "geoid_height",
    "set_geoid",
    # spatial_hierarchy
    "cube_cell_id_to_s2",
    "h3_children",
    "h3_compact",
    "h3_index_to_latlon",
    "h3_is_ancestor",
    "h3_is_valid_index",
    "h3_latlon_to_index",
    "h3_level_from_index",
    "h3_parent",
    "h3_region_cover",
    "h3_resolution_to_s2_level",
    "s2_is_ancestor",
    "s2_is_valid_token",
    "s2_level_from_token",
    "s2_level_to_h3_resolution",
    "s2_latlon_to_token",
    "s2_parent",
    "s2_region_cover",
    "s2_to_cube_sphere",
    "s2_token_to_latlon",
]
