"""Core models for the dual-timeline system."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from enum import StrEnum


class SignalKind(StrEnum):
    """Discriminates how a metric should be interpreted and resampled.

    CONTINUOUS: the phenomenon exists continuously (weight, sleep quality,
                CTL/ATL).  Interpolation is physically meaningful.
    EVENT:      discrete occurrences (meals, workouts, R-peak beats).
                Never interpolated; aggregated in windows instead.
    RATE:       derived from EVENT counts in a sliding window (bpm,
                steps/min).  Computed, not raw.
    """

    CONTINUOUS = "continuous"
    EVENT = "event"
    RATE = "rate"


@dataclass
class DataPoint:
    """Single measurement in long-format wellbeing storage.

    Attributes:
        timestamp:       UTC timestamp of the measurement.
        source:          Data source identifier (e.g. "garmin", "manual").
        metric:          Metric name (e.g. "weight_kg", "calories_kcal").
        value:           Measured value.  None = missing / not recorded.
        unit:            Physical unit (e.g. "kg", "bpm", "kcal").
        kind:            SignalKind — how this metric should be resampled.
        confidence:      0.0–1.0 reliability of this single measurement.
        is_interpolated: True if generated by interpolation, not measured.
    """

    timestamp: datetime
    source: str
    metric: str
    value: float | None
    unit: str = ""
    kind: SignalKind = SignalKind.CONTINUOUS
    confidence: float = 1.0
    is_interpolated: bool = False


@dataclass
class Track:
    """Container for all DataPoints of a single metric.

    Attributes:
        metric: Metric name (e.g. "weight_kg").
        kind:   SignalKind for this metric.
        points: Ordered list of DataPoints.
    """

    metric: str
    kind: SignalKind
    points: list[DataPoint]

    def sorted(self) -> list[DataPoint]:
        """Return points sorted by timestamp (ascending)."""
        return sorted(self.points, key=lambda p: p.timestamp)

    def count(self) -> int:
        return len(self.points)


@dataclass
class ClockTrack:
    """A subsystem's internal-clock time series.

    Attributes:
        subsystem:  Human-readable name (e.g. "metabolism", "stress").
        t_real:     Real-world timestamps (datetime list).
        phi:        Internal-clock values phi(t), monotone non-linear.
        alpha:      Per-step clock speed alpha(t) = dphi/dt approx.
        tau:        Time-constant tau(t) used at each step (seconds).
        confidence: Per-point confidence aligned with t_real.
    """

    subsystem: str
    t_real: list[datetime]
    phi: list[float]
    alpha: list[float]
    tau: list[float]
    confidence: list[float]


@dataclass
class SyncIndex:
    """Relationship between two ClockTracks.

    Attributes:
        subsystem_a:     First subsystem name.
        subsystem_b:     Second subsystem name.
        drift:           Cumulative drift phi_a - phi_b at each step.
        velocity_corr:   Pearson correlation of instantaneous velocities.
        lag_days:        Optimal cross-correlation lag (positive = B lags A).
        lag_correlation: Cross-correlation value at optimal lag.
        computed_at:     When the index was last recomputed.
        confidence:      Overall confidence (min of both tracks).
    """

    subsystem_a: str
    subsystem_b: str
    drift: list[float]
    velocity_corr: float
    lag_days: float
    lag_correlation: float
    computed_at: datetime
    confidence: float


@dataclass
class PhiConfig:
    """Configuration for the phi-clock builder.

    Attributes:
        tau_baseline: Base time-constant in seconds (default: 7 days).
        tau_min:      Minimum tau (fast clock, e.g. acute stress).
        tau_max:      Maximum tau (slow clock, deep recovery).
        grid_spacing: Resampling interval string (e.g. "1D", "6H").
        ema_alpha:    Smoothing factor for the EMA pre-filter on raw values.
    """

    tau_baseline: float = 604800.0
    tau_min: float = 86400.0
    tau_max: float = 1209600.0
    grid_spacing: str = "1D"
    ema_alpha: float = 0.3
